---
# dspace directories

base_dir: "/dspace"
dspace_base_dir: /dspace/dspace_build 
dspace_install_dir: /dspace
apache_server_hostname: repository.example.org
dspace_download_server: https://github.com/DSpace/DSpace/releases/download/dspace-6.3/dspace-6.3-src-release.tar.gz
directories_dir:
  - /dspace
    /dspace/dspace_build


