---
#customization 
- name: create administrator
  shell: "/dspace/bin/dspace create-administrator -e {{ admin_email }} -f {{ admin_firstname }} -l {{ admin_lastname }} -c {{ admin_language }} -p {{ admin_password }}"
  become: true
  #become_user: "{{ dspace_user }}"

- name: brand bootstrap variables
  template:
    src: templates/bootstrap_variables.scss.j2
    dest: "{{ full_theme_path }}/styles/classic_mirage_color_scheme/_bootstrap_variables.scss"
  notify: update styles

- name: brand additional styles
  template:
    src: templates/style.scss.j2
    dest: "{{ full_theme_path }}/styles/_style.scss"
  notify: update styles

- name: brand logo
  copy:
    src: "files/{{ logo }}"
    dest: "{{ full_theme_path }}/images/DSpace-logo-line.svg"
  notify: update styles