---
# download and unarchive dspace package.

- name: Download Dspace binaries
  get_url:
    url: "{{ dspace_download_server }}"
    dest: "{{ dspace_base_dir }}"
  register: bin_files
# extract downloaded dspace 
- name: Extrating the Dspace files
  unarchive:
    src: /dspace/dspace_build/dspace-6.3-src-release.tar.gz
    dest: /dspace/dspace_build/
    remote_src: yes
    #copy: no
 # with_items:
  #- "{{ bin_files.stdout }}"

  #Maven install
  
- name: dspace | build
  command: "mvn -U package chdir=/dspace/dspace_build/dspace-6.3-src-release"  

   

- name: dspace | perform fresh install
  command:  ant fresh_install chdir={{dspace_source_dir}}/dspace/target/dspace-6.3-build creates={{dspace_install_dir}}/webapps/xmlui
